[[main]]
  identifier = "about"
  name = "Acerca de"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archivos"
  url = "archive"
  weight = 2

[[main]]
  identifier = "presentation"
  name = "Presentaciones"
  url = "presentation"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "Galería"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "Caricaturas"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Fotos"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 5

[[main]]
  identifier = "showcase"
  name = "Casos"
  url = "showcase"
  weight = 6

[[main]]
  identifier = "publication"
  name = "Publicación"
  url = "publication"
  weight = 7